FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["HelloWorldApi.csproj", "./"]
RUN dotnet restore "./HelloWorldApi.csproj"
COPY . .
RUN dotnet build "HelloWorldApi.csproj" -c Release -o /app/build
RUN dotnet publish "HelloWorldApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "HelloWorldApi.dll"]
