apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cide-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cide-app
  source:
    path: terraform
    repoURL: https://github.com/kapoc3/cide_devops
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
